config/routes.rb
Produtividade::Application.routes.draw do
  resources :canals

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :skip => :registrations
  root :to => "entrantes#index"
  resources :nome_arquivos
  resources :nota_tecnicas
  resources :entrantes

end

app/models/entrante.rb
class Entrante < ActiveRecord::Base
	never_wastes
	validates_presence_of :prot_doc,
												:dt_prot_doc,
												:assunto, 
												:procedimento
	
	validates :processo_principal, presence: true, if: :procedimento_anexado?
	validate :valid_date?
 
  def procedimento_anexado?
    procedimento == "ANEXADO"
  end											

	def valid_date?
	  if Date.parse(dt_prot_doc) > Date.today
	  	errors.add(:dt_prot_doc, "Data maior do que a data de hoje.")
	  end
	end

	private
    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def entrante_params
      params.require(:dt_prot_doc)
    end
end

app/controllers/entrantes_controller.rb
class EntrantesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_entrante, only: [:show, :edit, :update, :destroy]

  # GET /entrantes
  # GET /entrantes.json
  def index
    @entrantes = Entrante.all
  end

  # GET /entrantes/new
  def new
    @entrante = Entrante.new
    @assunto = ['OUTORGA','PÓS-OUTORGA JURÍDICO','PÓS-OUTORGA TÉCNICO','RENOVAÇÃO','CANAL DA CIDADANIA']
  end

  # GET /entrantes/1/edit
  def edit
  end

  # POST /entrantes
  # POST /entrantes.json
  def create
    @entrante = Entrante.new(entrante_params)

    respond_to do |format|
      if @entrante.save
        format.html { redirect_to action: :index, notice: 'Ação criada com sucesso.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /entrantes/1
  # PATCH/PUT /entrantes/1.json
  def update
    respond_to do |format|
      if @entrante.update(entrante_params)
        format.html { redirect_to @entrante, notice: 'Entrante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrantes/1
  # DELETE /entrantes/1.json
  def destroy
    @entrante.destroy
    respond_to do |format|
      format.html { redirect_to entrantes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrante
      @entrante = Entrante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrante_params
      params.require(:entrante).permit(:prot_doc, :dt_prot_doc, :area, :assunto, :procedimento, :processo_principal, :dt_procedimento)
    end
end

app/views/entrantes/_form.html.slim
= simple_form_for(@entrante, html: {class: 'form-horizontal' }) do |f| 
  - if @entrante.errors.any? 
    #error_explanation
      h2 = pluralize(@entrante.errors.count, "error")
      | não permitiu esse processo de ser salvo

      ul 
        - @entrante.errors.full_messages.each do |msg| 
          li = msg
  div.form-group
    = f.label "Nº do Protocolo:"
    br
    = f.text_field :prot_doc
 
  div.form-group
    = f.input :dt_prot_doc, :placeholder => "#{Time.now.strftime("%d/%m/%Y")}", :label => "Data do Protocolo:", hint: 'Por padrão, data de hoje.'
 
  div.form-group
    = f.input :assunto, :collection => @assunto, :prompt => "Selecione", :label => "Assunto"
 
  div.form-group
    = f.input :procedimento, :collection => ['INSTAURADO', 'ANEXADO', 'ARQUIVADO', 'PUBLICADO', 'EXPEDIDO', 'ENCAMINHADO INTERNO', 'ENCAMINHADO ANATEL', 'ENTRANTE'], :prompt => "Selecione", :label => "Procedimento"
 
  div.form-group
    #processo_principal
      = f.label "Processo Principal"
      br
      = f.text_field :processo_principal

  div.actions
    = f.button :submit, "Criar Ação"

app/views/entrantes/index.html.slim
h1 Listagem de Ações
table.table.table-striped.table-hover
  thead
    tr
      th Nº do Protocolo
      th Data do Protocolo
      th Assunto
      th Procedimento
      th Processo Principal
      th Data Procedimento
      th
  tbody
    - @entrantes.each do |entrante| 
      tr
        td
          = entrante.prot_doc 
        td
          = entrante.dt_prot_doc 
        td
          = entrante.assunto 
        td
          = entrante.procedimento 
        td
          = entrante.processo_principal 
        td
          =l entrante.created_at
        td
          = link_to 'Apagar', entrante, method: :delete, data: { confirm: 'Tem certeza?' }, :class => 'btn btn-danger btn-xs'
br
= link_to '+ Ação', new_entrante_path, :class => 'btn btn-warning'

app/views/entrantes/new.html.slim
h1 Nova Ação
= render 'form'
= link_to 'Voltar', entrantes_path