config/routes.rb
Produtividade::Application.routes.draw do
  resources :canals

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :skip => :registrations
  root :to => "entrantes#index"
  resources :nome_arquivos
  resources :nota_tecnicas
  resources :entrantes

end

app/models/nota_tecnica.rb
class NotaTecnica < ActiveRecord::Base
	never_wastes
	validates_presence_of :data_nota,
										    :numero_nota,
										    :numero_processo,
										    :nome_do_analista

	validates :area,
            :presence => true,
            :inclusion => {:in => %w(LEGAL TÉCNICA), :message => "%{value} não é uma área válida"}

	validates :status,
            :presence => true,
             exclusion: { in: %w(Selecione), :message => "%{value} não é um status válido"}
end

app/controllers/nota_tecnicas_controller.rb
class NotaTecnicasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_nota_tecnica, only: [:show, :edit, :update, :destroy]

  # GET /nota_tecnicas
  # GET /nota_tecnicas.json
  def index
    @nota_tecnicas = NotaTecnica.all
  end

  # GET /nota_tecnicas/new
  def new
    @nota_tecnica = NotaTecnica.new
  end

  # GET /nota_tecnicas/1/edit
  def edit
  end

  # POST /nota_tecnicas
  # POST /nota_tecnicas.json
  def create
    @nota_tecnica = NotaTecnica.new(nota_tecnica_params)

    respond_to do |format|
      if @nota_tecnica.save
        format.html { redirect_to action: :index, notice: 'Nota Técnica criada com sucesso.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /nota_tecnicas/1
  # PATCH/PUT /nota_tecnicas/1.json
  def update
    respond_to do |format|
      if @nota_tecnica.update(nota_tecnica_params)
        format.html { redirect_to @nota_tecnica, notice: 'Nota tecnica was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nota_tecnica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota_tecnicas/1
  # DELETE /nota_tecnicas/1.json
  def destroy
    @nota_tecnica.destroy
    respond_to do |format|
      format.html { redirect_to nota_tecnicas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota_tecnica
      @nota_tecnica = NotaTecnica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_tecnica_params
      params.require(:nota_tecnica).permit(:data_nota, :numero_nota, :numero_processo, :status, :nome_do_analista, :area)
    end
end

app/helpers/nota_tecnicas_helper.rb
module NotaTecnicasHelper
end

app/views/nota_tecnicas/_form.html.slim
= simple_form_for(@nota_tecnica, html: {class: 'form-horizontal' }) do |f|
  - if @nota_tecnica.errors.any?
    #error_explanation
      h2 
        = pluralize(@nota_tecnica.errors.count, "error")
        | não permitiu esse processo de ser salvo:

      ul
        - @nota_tecnica.errors.full_messages.each do |msg|
          li
            = msg

  div.field
    = f.label "Nome do Analista" 
    br
    = f.text_field :nome_do_analista 
  div.field
    = f.input :area, :collection => ['TÉCNICA', 'LEGAL'], :prompt => "Selecione", :label => "Área" 
  div.field
    = f.input :data_nota, :as => :datetime_picker, :label => "Data da Nota Técnica:"
  div.field
    = f.label "Nº da Nota" 
    br
    = f.text_field :numero_nota 
  div.field
    = f.label "Nº do Processo" 
    br
    = f.text_field :numero_processo 
  div.field
    = f.input :status, :collection => ['DEFERIDO', 'INDEFERIDO', 'EXIGÊNCIA', 'OUTRAS PROVIDÊNCIAS', 'EXPEDIDO', 'ENCAMINHADO_INTERNO', 'ENCAMINHADO_ANATEL', 'ENTRANTE'], :prompt => "Selecione", :label => "Status" 
  div.actions
    = f.button :submit, "Nova Nota Técnica"

app/views/nota_tecnicas/index.html.slim
h1 Listagem de Notas Técnicas
table.table.table-striped.table-hover
  thead
    tr
      th Data da Nota
      th Nº Nota
      th Nº processo
      th Status
      th Nome do Analista
      th Área
      th
  tbody
    - @nota_tecnicas.each do |nota_tecnica| %
      tr
        td = nota_tecnica.data_nota
        td = nota_tecnica.numero_nota
        td = nota_tecnica.numero_processo
        td = nota_tecnica.status
        td = nota_tecnica.nome_do_analista
        td = nota_tecnica.area
        td = link_to 'Apagar', nota_tecnica, method: :delete, data: { confirm: 'Tem certeza?' }, :class => 'btn btn-danger btn-xs'
br
= link_to '+ Nota Técnica', new_nota_tecnica_path, :class => 'btn btn-warning'

app/views/nota_tecnicas/new.html.slim
h1 Nova Nota Técnica
= render 'form'
= link_to 'Voltar', nota_tecnicas_path