config/routes.rb
Produtividade::Application.routes.draw do
  resources :canals

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :skip => :registrations
  root :to => "entrantes#index"
  resources :nome_arquivos
  resources :nota_tecnicas
  resources :entrantes

end

app/models/nome_arquivo.rb
class NomeArquivo < ActiveRecord::Base
	never_wastes
end

app/controllers/nome_arquivos_controller.rb
class NomeArquivosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_nome_arquivo, only: [:show, :edit, :update, :destroy]

  # GET /nome_arquivos
  # GET /nome_arquivos.json
  def index
    @nome_arquivos = NomeArquivo.all
  end

  # GET /nome_arquivos/1
  # GET /nome_arquivos/1.json
  def show
  end

  # GET /nome_arquivos/new
  def new
    @nome_arquivo = NomeArquivo.new
    @assuntos = ["Alteracao de Canal",
                "Alteracao de Caracteristicas Tecnicas",
                "Alteracao de Coordenadas Geograficas",
                "Alteracao de Geradora RTV",
                "Alteracao de Potencia Mudanca de Classe",
                "Alteracao dos Objetivos Sociais",
                "Alteracao Simples",
                "Aprovacao de Atos Praticados",
                "Aprovacao de Locais e Equipamentos",
                "Aprovacao de Procurador",
                "Aprovacao de Quadro Diretivo",
                "Assentimento Previo",
                "Autorizacao de RTV Primaria",
                "Autorizacao de RTV Secundaria",
                "Aviso de Habilitacao FME",
                "Aviso de Habilitacao RTV",
                "Aviso de Habilitacao TVE",
                "Consignação de Canal Digital",
                "Consignação de Canal Uniao",
                "Contrato",
                "Declaracao de Composicao Societaria",
                "Enquadramento no Plano Basico",
                "Extincao de Outorga",
                "Extincao de Outorga RTV",
                "Inclusao de canal no Plano Basico",
                "Licenciamento",
                "Licitacao",
                "Mudanca do Transmissor",
                "Outorga FME",
                "Outorga TVE",
                "Renovacao de Outorga",
                "Revisao de Outorga",
                "Servico Especial para fins Cientificos e Experimentais",
                "Transferencia de Autorizacao RTV",
                "Transferencia de Local do Estudio",
                "Transferencia Direta",
                "Transferencia Indireta"]
  end

  # GET /nome_arquivos/1/edit
  def edit
  end

  # POST /nome_arquivos
  # POST /nome_arquivos.json
  def create
    @nome_arquivo = NomeArquivo.new(nome_arquivo_params)

    respond_to do |format|
      if @nome_arquivo.save
        format.html { redirect_to action: :index, notice: 'Nome de Arquivo criado.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /nome_arquivos/1
  # PATCH/PUT /nome_arquivos/1.json
  def update
    respond_to do |format|
      if @nome_arquivo.update(nome_arquivo_params)
        format.html { redirect_to @nome_arquivo, notice: 'Renomear was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nome_arquivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nome_arquivos/1
  # DELETE /nome_arquivos/1.json
  def destroy
    @nome_arquivo.destroy
    respond_to do |format|
      format.html { redirect_to nome_arquivos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nome_arquivo
      @nome_arquivo = NomeArquivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nome_arquivo_params
      params.require(:nome_arquivo).permit(:tipo, :assunto, :data, :cprod, :sem_cprod, :mais_de_um_processo, :arquivo)
    end
end

app/views/nome_arquivos/_form.html.slim
= simple_form_for(@nome_arquivo, html: {class: 'form-horizontal' }) do |f| 
  - if @nome_arquivo.errors.any? 
    #error_explanation
      h2
        = pluralize(@nome_arquivo.errors.count, "error")
        | não permitiu esse processo de ser salvo:

      ul
        - @nome_arquivo.errors.full_messages.each do |msg| 
          li
            = msg

  .field
    = f.input :tipo, :collection => ['AVISO','CONTRATO','CONVENIO','DECRETO','DESPACHO','EDITAL','MEMORANDO','NOTA INFORMATIVA','NOTA TÉCNICA','OFICIO','PORTARIA'], :prompt => "Selecione", :label => "Tipo do Documento"
  
  .field
    = f.input :assunto, :collection => @assuntos, :prompt => "Selecione", :label => "Assunto"
  
  .field
    = f.input :data, :as => :datetime_picker, :label => "Data:"
  
  .field
    = f.label "CPROD:"
    br
    = f.text_field :cprod 
  
  .field
    = f.label "Sem CPROD ?:"
    br
    = f.check_box :sem_cprod 
  
  .field
    = f.label "Mais de um processo ?:"
    br
    = f.check_box :mais_de_um_processo 
  
  .field
    = f.label "Arquivo:"
    br
    = f.text_field :arquivo 
  
  .actions
    = f.button :submit, "Novo Nome de arquivo"

app/views/nome_arquivos/index.html.slim
h1 Listagem de Nome
table.table.table-striped.table-hover
  thead 
    tr 
      th Tipo
      th Assunto
      th Data
      th Cprod
      th Sem cprod
      th Mais de um processo
      th Nome do Arquivo
      th
  tbody 
     - @nome_arquivos.each do |nome_arquivo|  
      tr 
        td = nome_arquivo.tipo  
        td = nome_arquivo.assunto  
        td = nome_arquivo.data.strftime("%m/%d/%Y")
        td = nome_arquivo.cprod  
        td = nome_arquivo.sem_cprod  
        td = nome_arquivo.mais_de_um_processo  
        td 
          button.btn.btn-info.btn-xs PDF
          | &nbsp;
          button.btn.btn-info.btn-xs DOC
        td = link_to 'Apagar', nome_arquivo, method: :delete, data: { confirm: 'Tem Certeza?' }, :class => 'btn btn-danger btn-xs'
br
= link_to '+ Nome de Arquivo', new_nome_arquivo_path, :class => 'btn btn-warning'

app/views/nome_arquivos/new.html.slim
h1 Novo Nome de Arquivo
= render 'form'
= link_to 'Voltar', nome_arquivos_path